// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ4Hnhp75pGcyuSkC8F-xGmuc_Ch8WfMs',
    appId: '1:412861240163:web:bfe5f8feacfb643a727956',
    messagingSenderId: '412861240163',
    projectId: 'on-de-band-demo',
    authDomain: 'on-de-band-demo.firebaseapp.com',
    storageBucket: 'on-de-band-demo.appspot.com',
    measurementId: 'G-3W0NNH305K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWUBKzzPOGCYz4Xy2EhsGnGNwG__HJSXk',
    appId: '1:412861240163:android:da8ae6301d84f7cf727956',
    messagingSenderId: '412861240163',
    projectId: 'on-de-band-demo',
    storageBucket: 'on-de-band-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr9kJPFUg2mcNT5zL93pNYtKQXa4k1utU',
    appId: '1:412861240163:ios:dd4085ebebf26c57727956',
    messagingSenderId: '412861240163',
    projectId: 'on-de-band-demo',
    storageBucket: 'on-de-band-demo.appspot.com',
    iosClientId: '412861240163-khqf9acorkrdsrhukamj4hqpkaeask23.apps.googleusercontent.com',
    iosBundleId: 'com.example.onDeBandDemoChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr9kJPFUg2mcNT5zL93pNYtKQXa4k1utU',
    appId: '1:412861240163:ios:dd4085ebebf26c57727956',
    messagingSenderId: '412861240163',
    projectId: 'on-de-band-demo',
    storageBucket: 'on-de-band-demo.appspot.com',
    iosClientId: '412861240163-khqf9acorkrdsrhukamj4hqpkaeask23.apps.googleusercontent.com',
    iosBundleId: 'com.example.onDeBandDemoChat',
  );
}
